### PR TITLE
Done payment integration

### PR DESCRIPTION
**Pull request by MuskanChhatrasal**
Done with payment integration

### CODE REVIEW

**Review by Developers-codz — APPROVED** [review]
Looks good to go !!! Nice that you added payment integration 
One thing that I noticed it on refresh the link broke for fixing that do add `_redirect` file in your public folder

**Review by aayushjain-code — APPROVED** [review]
Nice Work on the UI Payment link also working!

**Comment by MuskanChhatrasal** [comment]
Thankyou for reviewing. Will surely _redirect file

**Comment by MuskanChhatrasal** [comment]
Thankyou for reviewing!!

**Pull request merged**
